"""empty message

Revision ID: 0911fa97bf5d
Revises: fe239a631d9c
Create Date: 2023-10-01 00:53:59.476398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0911fa97bf5d'
down_revision = 'fe239a631d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('dataPath', sa.String(length=80), nullable=True),
    sa.Column('imagePath', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['pass_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reports')
    # ### end Alembic commands ###
