"""initial migration

Revision ID: 26871be19c20
Revises: 
Create Date: 2023-07-17 22:19:18.484899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26871be19c20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('satellite',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('Name', sa.String(length=50), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('Name')
    # )
    # op.create_table('pass_data',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('AOS', sa.DateTime(), nullable=True),
    # sa.Column('LOS', sa.DateTime(), nullable=True),
    # sa.Column('maxElevation', sa.Integer(), nullable=True),
    # sa.Column('ScheduledToReceive', sa.Boolean(), nullable=True),
    # sa.Column('SatetlliteName', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['SatetlliteName'], ['satellite.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('pass_data', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_pass_data_AOS'), ['AOS'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('pass_data', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_pass_data_AOS'))
    pass
    # op.drop_table('pass_data')
    # op.drop_table('satellite')
    # ### end Alembic commands ###
