"""added TLE in Reports

Revision ID: 5cc58656183a
Revises: 61088733377d
Create Date: 2024-01-03 12:29:09.932019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc58656183a'
down_revision = '61088733377d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TLELine1', sa.String(length=70), nullable=True))
        batch_op.add_column(sa.Column('TLELine2', sa.String(length=70), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reports', schema=None) as batch_op:
        batch_op.drop_column('TLELine2')
        batch_op.drop_column('TLELine1')

    # ### end Alembic commands ###
