"""empty message

Revision ID: 633027f41d65
Revises: 30ed7a2796b9
Create Date: 2024-03-15 23:45:31.022047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633027f41d65'
down_revision = '30ed7a2796b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
