"""Set pass scheduling to true by default

Revision ID: c4c9b69456db
Revises: db81fe5190f4
Create Date: 2023-08-18 13:07:51.913328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c9b69456db'
down_revision = 'db81fe5190f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('satellite', schema=None) as batch_op:
        batch_op.alter_column('Norad_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('satellite', schema=None) as batch_op:
        batch_op.alter_column('Norad_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
