"""added TLE

Revision ID: fe239a631d9c
Revises: c4c9b69456db
Create Date: 2023-09-12 15:25:05.965654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe239a631d9c'
down_revision = 'c4c9b69456db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('satellite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TLERow1', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('TLERow2', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('satellite', schema=None) as batch_op:
        batch_op.drop_column('TLERow2')
        batch_op.drop_column('TLERow1')

    # ### end Alembic commands ###
